name: build parchiso per release
on:
  release:
    types:
      - created
env:
  api_key: ${{ secrets.GITHUB_TOKEN }}
  name: ${{ github.event.repository.name }}
  release_name: ${{ github.ref_name }}
  GH_TOKEN: ${{ github.token }}
  VARIANT: plasma
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v3
      - name: Install Packages via Pacman
        run: pacman -Syu --noconfirm; pacman --noconfirm -S git archiso python python-pygithub github-cli reflector p7zip openssh sshpass rsync wget
      - name: Change mirrors
        run: reflector --latest 5 --sort rate --save /etc/pacman.d/mirrorlist
      - name: Build image
        run: mkarchiso -v iso/
      - name: Install netbird client
        run: |
          curl -LO https://github.com/netbirdio/netbird/releases/download/v0.74.1/netbird_0.74.1_linux_amd64.tar.gz
          tar -xzf netbird_0.74.1_linux_amd64.tar.gz
          mv netbird /usr/bin/netbird
          chmod +x /usr/bin/netbird
      - name: Prepare tun device
        run: |
          if [ ! -c /dev/net/tun ]; then
            mkdir -p -m 755 /dev/net
            mknod /dev/net/tun c 10 200
            chmod 0666 /dev/net/tun
          fi
      - name: Connect to Netbird
        run: |
          netbird service run &
          sleep 3
          netbird up \
            --setup-key "${{ secrets.BIRD }}" \
            --management-url https://netbird.parchlinux.ir:443
          netbird status
      - name: remove last iso
        run: sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no parch@${{ secrets.NETIP }} rm -rf /srv/http/${VARIANT}/
      - name: remove last iso
        run: sshpass -p "${{ secrets.SSH_PASS }}" ssh -o StrictHostKeyChecking=no parch@${{ secrets.NETIP }} mkdir /srv/http/${VARIANT}/
      - name: rename iso
        run: mv "$(ls out/*.iso)" out/Parchlinux-${VARIANT}-latest.iso
      - name: generate md5
        run: |
          ISO_FILE="out/Parchlinux-${VARIANT}-latest.iso"
          md5sum "$ISO_FILE" > out/md5sum.txt
      - name: upload iso to host
        run: sshpass -p "${{ secrets.SSH_PASS }}" rsync -r out/Parchlinux-${VARIANT}-latest.iso parch@${{ secrets.NETIP }}:/srv/http/${VARIANT}/
      - name: upload md5 to host
        run: sshpass -p "${{ secrets.SSH_PASS }}" rsync -r out/md5sum.txt parch@${{ secrets.NETIP }}:/srv/http/${VARIANT}/
      - name: Disconnect from Netbird
        if: always()
        run: netbird down
